version: "2"
services:
  app:
    build: ./app
    depends_on:
      - "db"
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro